-- Generated by build_schema.py. Scope: Nhom8_ChucNang.docx (25 functions).
-- MySQL 8.0.16+, InnoDB, utf8mb4. Fresh database; no DROP statements.
CREATE DATABASE IF NOT EXISTS `bookmooch_db_v3` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `bookmooch_db_v3`;
SET NAMES utf8mb4;

CREATE TABLE `users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `email` VARCHAR(150) NOT NULL UNIQUE,
  `password_hash` VARCHAR(255) NULL,
  `google_sub` VARCHAR(255) NULL UNIQUE,
  `full_name` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `avatar_url` TEXT NULL,
  `role` VARCHAR(20) NOT NULL DEFAULT 'USER',
  `is_seller` BOOLEAN NOT NULL DEFAULT false,
  `account_status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  CONSTRAINT `ck_user_login_identity` CHECK (password_hash IS NOT NULL OR google_sub IS NOT NULL),
  CONSTRAINT `ck_users_role` CHECK (role IN ('USER', 'ADMIN')),
  CONSTRAINT `ck_users_account_status` CHECK (account_status IN ('ACTIVE', 'LOCKED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `auth_sessions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` BIGINT NOT NULL,
  `token_hash` CHAR(64) NOT NULL UNIQUE,
  `expires_at` DATETIME NOT NULL,
  `revoked_at` DATETIME NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY `idx_session_user_expiry` (`user_id`, `expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `password_reset_tokens` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` BIGINT NOT NULL,
  `token_hash` CHAR(64) NOT NULL UNIQUE,
  `expires_at` DATETIME NOT NULL,
  `used_at` DATETIME NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `categories` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `slug` VARCHAR(120) NOT NULL UNIQUE,
  `parent_id` INT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `authors` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(150) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `publishers` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(150) NOT NULL,
  `slug` VARCHAR(160) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `products` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `seller_id` BIGINT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL UNIQUE,
  `description` TEXT NOT NULL,
  `cover_image_url` TEXT NULL,
  `category_id` INT NOT NULL,
  `author_id` INT NULL,
  `publisher_id` INT NULL,
  `volume_numbers` VARCHAR(100) NULL,
  `edition_type` VARCHAR(50) NULL,
  `publication_year` INT NULL,
  `condition_percent` INT NOT NULL,
  `price` DECIMAL(15,2) NOT NULL,
  `stock_quantity` INT NOT NULL DEFAULT 1,
  `listing_type` VARCHAR(20) NOT NULL DEFAULT 'SELL',
  `trade_wish_note` TEXT NULL,
  `is_active` BOOLEAN NOT NULL DEFAULT true,
  `moderation_status` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  `moderated_by` BIGINT NULL,
  `moderation_reason` TEXT NULL,
  `moderated_at` DATETIME NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  UNIQUE KEY `uq_product_owner` (`id`, `seller_id`),
  KEY `idx_product_latest` (`moderation_status`, `is_active`, `created_at`),
  KEY `idx_product_filter` (`category_id`, `price`),
  KEY `idx_seller_products` (`seller_id`, `created_at`),
  CONSTRAINT `ck_products_condition_percent` CHECK (condition_percent BETWEEN 0 AND 100),
  CONSTRAINT `ck_products_price` CHECK (price >= 0),
  CONSTRAINT `ck_products_stock_quantity` CHECK (stock_quantity >= 0),
  CONSTRAINT `ck_products_listing_type` CHECK (listing_type IN ('SELL', 'TRADE', 'SELL_AND_TRADE')),
  CONSTRAINT `ck_products_moderation_status` CHECK (moderation_status IN ('PENDING', 'APPROVED', 'REJECTED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_images` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `product_id` BIGINT NOT NULL,
  `image_url` TEXT NOT NULL,
  `image_type` VARCHAR(10) NOT NULL DEFAULT 'DETAIL',
  `display_order` INT NOT NULL DEFAULT 0,
  UNIQUE KEY `uq_product_image_order` (`product_id`, `display_order`),
  CONSTRAINT `ck_product_images_image_type` CHECK (image_type IN ('COVER', 'DETAIL')),
  CONSTRAINT `ck_product_images_display_order` CHECK (display_order >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `carts` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` BIGINT NOT NULL UNIQUE,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `cart_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `cart_id` BIGINT NOT NULL,
  `product_id` BIGINT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  `is_selected` BOOLEAN NOT NULL DEFAULT true,
  UNIQUE KEY `uq_cart_product` (`cart_id`, `product_id`),
  CONSTRAINT `ck_cart_items_quantity` CHECK (quantity > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `checkout_batches` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `checkout_code` VARCHAR(60) NOT NULL UNIQUE,
  `buyer_id` BIGINT NOT NULL,
  `idempotency_key` VARCHAR(100) NOT NULL UNIQUE,
  `total_amount` DECIMAL(15,2) NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `ck_checkout_batches_total_amount` CHECK (total_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `orders` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `order_code` VARCHAR(60) NOT NULL UNIQUE,
  `checkout_id` BIGINT NOT NULL,
  `buyer_id` BIGINT NOT NULL,
  `seller_id` BIGINT NOT NULL,
  `subtotal_amount` DECIMAL(15,2) NOT NULL,
  `shipping_fee` DECIMAL(15,2) NOT NULL DEFAULT 0,
  `total_amount` DECIMAL(15,2) NOT NULL,
  `recipient_name` VARCHAR(100) NOT NULL,
  `recipient_phone` VARCHAR(20) NOT NULL,
  `shipping_address` TEXT NOT NULL,
  `buyer_note` TEXT NULL,
  `status` VARCHAR(25) NOT NULL DEFAULT 'WAITING_PAYMENT',
  `payment_status` VARCHAR(25) NOT NULL DEFAULT 'PENDING',
  `cancelled_by` BIGINT NULL,
  `cancel_reason` TEXT NULL,
  `cancelled_at` DATETIME NULL,
  `stock_released_at` DATETIME NULL,
  `completed_at` DATETIME NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_buyer_history` (`buyer_id`, `created_at`),
  KEY `idx_seller_orders` (`seller_id`, `status`, `created_at`),
  KEY `idx_order_reports` (`status`, `completed_at`),
  CONSTRAINT `ck_order_total` CHECK (total_amount = subtotal_amount + shipping_fee),
  CONSTRAINT `ck_orders_subtotal_amount` CHECK (subtotal_amount >= 0),
  CONSTRAINT `ck_orders_shipping_fee` CHECK (shipping_fee >= 0),
  CONSTRAINT `ck_orders_total_amount` CHECK (total_amount >= 0),
  CONSTRAINT `ck_orders_status` CHECK (status IN ('WAITING_PAYMENT', 'WAITING_CONFIRM', 'PACKING', 'SHIPPING', 'DELIVERED', 'COMPLETED', 'CANCELLED')),
  CONSTRAINT `ck_orders_payment_status` CHECK (payment_status IN ('PENDING', 'PAID', 'PARTIALLY_REFUNDED', 'REFUNDED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `order_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `order_id` BIGINT NOT NULL,
  `product_id` BIGINT NOT NULL,
  `product_title` VARCHAR(255) NOT NULL,
  `image_url` TEXT NULL,
  `condition_percent` INT NOT NULL,
  `unit_price` DECIMAL(15,2) NOT NULL,
  `quantity` INT NOT NULL,
  UNIQUE KEY `uq_order_product` (`order_id`, `product_id`),
  CONSTRAINT `ck_order_items_condition_percent` CHECK (condition_percent BETWEEN 0 AND 100),
  CONSTRAINT `ck_order_items_unit_price` CHECK (unit_price >= 0),
  CONSTRAINT `ck_order_items_quantity` CHECK (quantity > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `order_status_history` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `order_id` BIGINT NOT NULL,
  `previous_status` VARCHAR(25) NULL,
  `new_status` VARCHAR(25) NOT NULL,
  `changed_by` BIGINT NULL,
  `note` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `payments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `payment_code` VARCHAR(60) NOT NULL UNIQUE,
  `checkout_id` BIGINT NOT NULL,
  `method` VARCHAR(20) NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  `provider_transaction_id` VARCHAR(150) NULL,
  `idempotency_key` VARCHAR(100) NOT NULL UNIQUE,
  `paid_at` DATETIME NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `uq_payment_provider` (`method`, `provider_transaction_id`),
  CONSTRAINT `ck_payments_method` CHECK (method IN ('VNPAY', 'MOMO', 'VIETQR', 'CREDIT_CARD')),
  CONSTRAINT `ck_payments_amount` CHECK (amount > 0),
  CONSTRAINT `ck_payments_status` CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED', 'EXPIRED', 'CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `payment_allocations` (
  `payment_id` BIGINT NOT NULL,
  `order_id` BIGINT NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`payment_id`, `order_id`),
  CONSTRAINT `ck_payment_allocations_amount` CHECK (amount > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `payment_events` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `payment_id` BIGINT NOT NULL,
  `provider_event_id` VARCHAR(150) NOT NULL,
  `event_type` VARCHAR(50) NOT NULL,
  `signature_verified` BOOLEAN NOT NULL DEFAULT false,
  `processed_at` DATETIME NULL,
  `received_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `uq_payment_event` (`payment_id`, `provider_event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `refunds` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `refund_code` VARCHAR(60) NOT NULL UNIQUE,
  `payment_id` BIGINT NOT NULL,
  `order_id` BIGINT NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  `idempotency_key` VARCHAR(100) NOT NULL UNIQUE,
  `provider_refund_id` VARCHAR(150) NULL UNIQUE,
  `failure_reason` TEXT NULL,
  `completed_at` DATETIME NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `ck_refunds_amount` CHECK (amount > 0),
  CONSTRAINT `ck_refunds_status` CHECK (status IN ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `reviews` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `order_item_id` BIGINT NOT NULL UNIQUE,
  `buyer_id` BIGINT NOT NULL,
  `rating` INT NOT NULL,
  `content` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `ck_reviews_rating` CHECK (rating BETWEEN 1 AND 5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `review_replies` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `review_id` BIGINT NOT NULL UNIQUE,
  `seller_id` BIGINT NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `loyalty_accounts` (
  `user_id` BIGINT NOT NULL PRIMARY KEY,
  `points_balance` BIGINT NOT NULL DEFAULT 0,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `ck_loyalty_accounts_points_balance` CHECK (points_balance >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `loyalty_transactions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` BIGINT NOT NULL,
  `order_id` BIGINT NOT NULL,
  `transaction_type` VARCHAR(20) NOT NULL,
  `points_delta` BIGINT NOT NULL,
  `balance_after` BIGINT NOT NULL,
  `idempotency_key` VARCHAR(100) NOT NULL UNIQUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `ck_loyalty_sign` CHECK ((transaction_type = 'EARN' AND points_delta > 0) OR (transaction_type = 'REVERSAL' AND points_delta < 0)),
  CONSTRAINT `ck_loyalty_transactions_transaction_type` CHECK (transaction_type IN ('EARN', 'REVERSAL')),
  CONSTRAINT `ck_loyalty_transactions_points_delta` CHECK (points_delta <> 0),
  CONSTRAINT `ck_loyalty_transactions_balance_after` CHECK (balance_after >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `exchange_rooms` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `room_code` VARCHAR(60) NOT NULL UNIQUE,
  `host_id` BIGINT NOT NULL,
  `target_product_id` BIGINT NOT NULL,
  `selected_offer_id` BIGINT NULL UNIQUE,
  `status` VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `closed_at` DATETIME NULL,
  UNIQUE KEY `uq_room_selected_offer` (`selected_offer_id`, `id`),
  CONSTRAINT `ck_exchange_rooms_status` CHECK (status IN ('OPEN', 'AGREED', 'COMPLETED', 'CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `exchange_room_members` (
  `room_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `joined_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`room_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `exchange_offers` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `room_id` BIGINT NOT NULL,
  `buyer_id` BIGINT NOT NULL,
  `cash_compensation` DECIMAL(15,2) NOT NULL DEFAULT 0,
  `compensation_payer_id` BIGINT NULL,
  `note` TEXT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  `buyer_confirmed` BOOLEAN NOT NULL DEFAULT false,
  `host_confirmed` BOOLEAN NOT NULL DEFAULT false,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `responded_at` DATETIME NULL,
  UNIQUE KEY `uq_offer_room` (`id`, `room_id`),
  CONSTRAINT `ck_offer_compensation` CHECK ((cash_compensation = 0 AND compensation_payer_id IS NULL) OR (cash_compensation > 0 AND compensation_payer_id IS NOT NULL)),
  CONSTRAINT `ck_exchange_offers_cash_compensation` CHECK (cash_compensation >= 0),
  CONSTRAINT `ck_exchange_offers_status` CHECK (status IN ('PENDING', 'ACCEPTED', 'DECLINED', 'WITHDRAWN'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `exchange_offer_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `offer_id` BIGINT NOT NULL,
  `product_id` BIGINT NOT NULL,
  `owner_id` BIGINT NOT NULL,
  `quantity` INT NOT NULL,
  `title_snapshot` VARCHAR(255) NOT NULL,
  `condition_snapshot` INT NOT NULL,
  UNIQUE KEY `uq_offer_product` (`offer_id`, `product_id`),
  CONSTRAINT `ck_exchange_offer_items_quantity` CHECK (quantity > 0),
  CONSTRAINT `ck_exchange_offer_items_condition_snapshot` CHECK (condition_snapshot BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `exchange_messages` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `room_id` BIGINT NOT NULL,
  `sender_id` BIGINT NOT NULL,
  `content` TEXT NULL,
  `image_url` TEXT NULL,
  `client_message_key` VARCHAR(100) NULL UNIQUE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY `idx_exchange_chat` (`room_id`, `id`),
  CONSTRAINT `ck_exchange_message_content` CHECK (content IS NOT NULL OR image_url IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_image_features` (
  `image_id` BIGINT NOT NULL PRIMARY KEY,
  `embedding` JSON NOT NULL,
  `model_name` VARCHAR(100) NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `ck_image_embedding` CHECK (JSON_TYPE(embedding) = 'ARRAY' AND JSON_LENGTH(embedding) > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_classifications` (
  `product_id` BIGINT NOT NULL PRIMARY KEY,
  `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  `is_comic` BOOLEAN NULL,
  `confidence` DECIMAL(5,4) NULL,
  `model_name` VARCHAR(100) NULL,
  `classified_at` DATETIME NULL,
  `error_message` TEXT NULL,
  CONSTRAINT `ck_classification_result` CHECK (status <> 'SUCCEEDED' OR (is_comic IS NOT NULL AND confidence IS NOT NULL AND model_name IS NOT NULL AND classified_at IS NOT NULL)),
  CONSTRAINT `ck_product_classifications_status` CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED')),
  CONSTRAINT `ck_product_classifications_confidence` CHECK (confidence BETWEEN 0 AND 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `consultation_sessions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` BIGINT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `consultation_messages` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `session_id` BIGINT NOT NULL,
  `sender_type` VARCHAR(20) NOT NULL,
  `content` TEXT NOT NULL,
  `suggested_product_ids` JSON NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY `idx_consultation_chat` (`session_id`, `id`),
  CONSTRAINT `ck_consultation_messages_sender_type` CHECK (sender_type IN ('USER', 'ASSISTANT'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `notifications` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` BIGINT NOT NULL,
  `order_id` BIGINT NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `content` TEXT NOT NULL,
  `deduplication_key` VARCHAR(150) NOT NULL UNIQUE,
  `read_at` DATETIME NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `auth_sessions` ADD CONSTRAINT `fk_auth_sessions_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
ALTER TABLE `password_reset_tokens` ADD CONSTRAINT `fk_password_reset_tokens_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
ALTER TABLE `categories` ADD CONSTRAINT `fk_categories_parent_id` FOREIGN KEY (`parent_id`) REFERENCES `categories` (`id`);
ALTER TABLE `products` ADD CONSTRAINT `fk_products_seller_id` FOREIGN KEY (`seller_id`) REFERENCES `users` (`id`);
ALTER TABLE `products` ADD CONSTRAINT `fk_products_category_id` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`);
ALTER TABLE `products` ADD CONSTRAINT `fk_products_author_id` FOREIGN KEY (`author_id`) REFERENCES `authors` (`id`);
ALTER TABLE `products` ADD CONSTRAINT `fk_products_publisher_id` FOREIGN KEY (`publisher_id`) REFERENCES `publishers` (`id`);
ALTER TABLE `products` ADD CONSTRAINT `fk_products_moderated_by` FOREIGN KEY (`moderated_by`) REFERENCES `users` (`id`);
ALTER TABLE `product_images` ADD CONSTRAINT `fk_product_images_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`);
ALTER TABLE `carts` ADD CONSTRAINT `fk_carts_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
ALTER TABLE `cart_items` ADD CONSTRAINT `fk_cart_items_cart_id` FOREIGN KEY (`cart_id`) REFERENCES `carts` (`id`);
ALTER TABLE `cart_items` ADD CONSTRAINT `fk_cart_items_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`);
ALTER TABLE `checkout_batches` ADD CONSTRAINT `fk_checkout_batches_buyer_id` FOREIGN KEY (`buyer_id`) REFERENCES `users` (`id`);
ALTER TABLE `orders` ADD CONSTRAINT `fk_orders_checkout_id` FOREIGN KEY (`checkout_id`) REFERENCES `checkout_batches` (`id`);
ALTER TABLE `orders` ADD CONSTRAINT `fk_orders_buyer_id` FOREIGN KEY (`buyer_id`) REFERENCES `users` (`id`);
ALTER TABLE `orders` ADD CONSTRAINT `fk_orders_seller_id` FOREIGN KEY (`seller_id`) REFERENCES `users` (`id`);
ALTER TABLE `orders` ADD CONSTRAINT `fk_orders_cancelled_by` FOREIGN KEY (`cancelled_by`) REFERENCES `users` (`id`);
ALTER TABLE `order_items` ADD CONSTRAINT `fk_order_items_order_id` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`);
ALTER TABLE `order_items` ADD CONSTRAINT `fk_order_items_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`);
ALTER TABLE `order_status_history` ADD CONSTRAINT `fk_order_status_history_order_id` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`);
ALTER TABLE `order_status_history` ADD CONSTRAINT `fk_order_status_history_changed_by` FOREIGN KEY (`changed_by`) REFERENCES `users` (`id`);
ALTER TABLE `payments` ADD CONSTRAINT `fk_payments_checkout_id` FOREIGN KEY (`checkout_id`) REFERENCES `checkout_batches` (`id`);
ALTER TABLE `payment_allocations` ADD CONSTRAINT `fk_payment_allocations_payment_id` FOREIGN KEY (`payment_id`) REFERENCES `payments` (`id`);
ALTER TABLE `payment_allocations` ADD CONSTRAINT `fk_payment_allocations_order_id` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`);
ALTER TABLE `payment_events` ADD CONSTRAINT `fk_payment_events_payment_id` FOREIGN KEY (`payment_id`) REFERENCES `payments` (`id`);
ALTER TABLE `refunds` ADD CONSTRAINT `fk_refund_paid_order` FOREIGN KEY (`payment_id`, `order_id`) REFERENCES `payment_allocations` (`payment_id`, `order_id`);
ALTER TABLE `reviews` ADD CONSTRAINT `fk_reviews_order_item_id` FOREIGN KEY (`order_item_id`) REFERENCES `order_items` (`id`);
ALTER TABLE `reviews` ADD CONSTRAINT `fk_reviews_buyer_id` FOREIGN KEY (`buyer_id`) REFERENCES `users` (`id`);
ALTER TABLE `review_replies` ADD CONSTRAINT `fk_review_replies_review_id` FOREIGN KEY (`review_id`) REFERENCES `reviews` (`id`);
ALTER TABLE `review_replies` ADD CONSTRAINT `fk_review_replies_seller_id` FOREIGN KEY (`seller_id`) REFERENCES `users` (`id`);
ALTER TABLE `loyalty_accounts` ADD CONSTRAINT `fk_loyalty_accounts_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
ALTER TABLE `loyalty_transactions` ADD CONSTRAINT `fk_loyalty_transactions_user_id` FOREIGN KEY (`user_id`) REFERENCES `loyalty_accounts` (`user_id`);
ALTER TABLE `loyalty_transactions` ADD CONSTRAINT `fk_loyalty_transactions_order_id` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`);
ALTER TABLE `exchange_rooms` ADD CONSTRAINT `fk_exchange_rooms_host_id` FOREIGN KEY (`host_id`) REFERENCES `users` (`id`);
ALTER TABLE `exchange_rooms` ADD CONSTRAINT `fk_room_product_owner` FOREIGN KEY (`target_product_id`, `host_id`) REFERENCES `products` (`id`, `seller_id`);
ALTER TABLE `exchange_room_members` ADD CONSTRAINT `fk_exchange_room_members_room_id` FOREIGN KEY (`room_id`) REFERENCES `exchange_rooms` (`id`);
ALTER TABLE `exchange_room_members` ADD CONSTRAINT `fk_exchange_room_members_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
ALTER TABLE `exchange_offers` ADD CONSTRAINT `fk_offer_room_member` FOREIGN KEY (`room_id`, `buyer_id`) REFERENCES `exchange_room_members` (`room_id`, `user_id`);
ALTER TABLE `exchange_offers` ADD CONSTRAINT `fk_exchange_offers_compensation_payer_id` FOREIGN KEY (`compensation_payer_id`) REFERENCES `users` (`id`);
ALTER TABLE `exchange_rooms` ADD CONSTRAINT `fk_room_selected_offer` FOREIGN KEY (`selected_offer_id`, `id`) REFERENCES `exchange_offers` (`id`, `room_id`);
ALTER TABLE `exchange_offer_items` ADD CONSTRAINT `fk_exchange_offer_items_offer_id` FOREIGN KEY (`offer_id`) REFERENCES `exchange_offers` (`id`);
ALTER TABLE `exchange_offer_items` ADD CONSTRAINT `fk_offer_product_owner` FOREIGN KEY (`product_id`, `owner_id`) REFERENCES `products` (`id`, `seller_id`);
ALTER TABLE `exchange_messages` ADD CONSTRAINT `fk_message_room_member` FOREIGN KEY (`room_id`, `sender_id`) REFERENCES `exchange_room_members` (`room_id`, `user_id`);
ALTER TABLE `product_image_features` ADD CONSTRAINT `fk_product_image_features_image_id` FOREIGN KEY (`image_id`) REFERENCES `product_images` (`id`);
ALTER TABLE `product_classifications` ADD CONSTRAINT `fk_product_classifications_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`);
ALTER TABLE `consultation_sessions` ADD CONSTRAINT `fk_consultation_sessions_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
ALTER TABLE `consultation_messages` ADD CONSTRAINT `fk_consultation_messages_session_id` FOREIGN KEY (`session_id`) REFERENCES `consultation_sessions` (`id`);
ALTER TABLE `notifications` ADD CONSTRAINT `fk_notifications_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
ALTER TABLE `notifications` ADD CONSTRAINT `fk_notifications_order_id` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`);
