"""Small shared model/SQL/DBML writer. No external packages required."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent
TABLES = {}
REFS = []
GROUPS = {
    'tg_auth': ('#2563EB', []),
    'tg_catalog': ('#059669', []),
    'tg_orders_payments': ('#EA580C', []),
    'tg_reviews_points': ('#CA8A04', []),
    'tg_exchange': ('#9333EA', []),
    'tg_ai': ('#0891B2', []),
    'tg_notifications': ('#DB2777', []),
}


def table(name, body, group):
    assert name not in TABLES
    columns = {}
    for line in body.strip().splitlines():
        m = re.fullmatch(r'\s*(\w+)\s+(\w+(?:\([^)]*\))?)(?:\s+\[(.*)\])?\s*', line)
        if not m:
            raise ValueError(line)
        column, dtype, settings = m.groups()
        settings = settings or ''
        def attr(key):
            match = re.search(rf'\b{key}:\s*(`[^`]*`|\'(?:\\.|[^\'])*\'|[^,\]]+)', settings)
            return match.group(1).strip() if match else None
        columns[column] = dict(name=column, type=dtype, pk=bool(re.search(r'\bpk\b', settings)),
                               nullable='not null' not in settings, unique=bool(re.search(r'\bunique\b', settings)),
                               increment='increment' in settings, default=attr('default'), check=attr('check'),
                               note=attr('note'), on_update=column == 'updated_at')
    TABLES[name] = dict(columns=columns, indexes=[], checks=[], note=None)
    GROUPS[group][1].append(name)


def index(name, columns, unique=False, pk=False, key=None):
    TABLES[name]['indexes'].append(dict(columns=columns.split(','), unique=unique, pk=pk, name=key))


def check(name, key, expression):
    TABLES[name]['checks'].append((key, expression))


def note(name, value):
    TABLES[name]['note'] = value


def fk(child, columns, parent, targets='id', key=None):
    REFS.append(dict(child=child, columns=columns.split(','), parent=parent, targets=targets.split(','),
                     name=key or 'fk_' + child + '_' + columns.replace(',', '_')))


def quote(value):
    return "'" + value.replace('\\', '\\\\').replace("'", "\\'") + "'"


def identifiers(columns):
    return ', '.join('`' + c + '`' for c in columns)


def validate():
    for name, t in TABLES.items():
        assert any(c['pk'] for c in t['columns'].values()) or any(i['pk'] for i in t['indexes']), name
        for i in t['indexes']:
            assert set(i['columns']) <= t['columns'].keys(), (name, i)
    keys = set()
    for r in REFS:
        assert r['name'] not in keys and len(r['name']) <= 64, r['name']
        keys.add(r['name'])
        assert len(r['columns']) == len(r['targets'])
        for a, b in zip(r['columns'], r['targets']):
            assert TABLES[r['child']]['columns'][a]['type'] == TABLES[r['parent']]['columns'][b]['type'], r
        parent = TABLES[r['parent']]
        unique_keys = [{c['name']} for c in parent['columns'].values() if c['pk'] or c['unique']]
        unique_keys += [set(i['columns']) for i in parent['indexes'] if i['pk'] or i['unique']]
        assert set(r['targets']) in unique_keys, ('Referenced key must be unique', r)
    for name in GROUPS:
        assert re.fullmatch(r'[A-Za-z_][A-Za-z0-9_]*', name), name


def emit():
    validate()
    sql = ['-- Generated by build_schema.py. Scope: Nhom8_ChucNang.docx (25 functions).',
           '-- MySQL 8.0.16+, InnoDB, utf8mb4. Fresh database; no DROP statements.',
           'CREATE DATABASE IF NOT EXISTS `bookmooch_db_v3` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;',
           'USE `bookmooch_db_v3`;', 'SET NAMES utf8mb4;', '']
    dbml = ['// Scope: Nhom8_ChucNang.docx. Generated by build_schema.py.',
            "Project comicworm_functions {\n  database_type: 'MySQL'\n  Note: 'Database phục vụ 25 chức năng trong Nhom8_ChucNang.docx. SQL: schema.sql. ON UPDATE CURRENT_TIMESTAMP ghi trong note. AI thực hiện tại backend, database lưu dữ liệu đầu vào/kết quả.'\n}\n"]
    for group, (_, names) in GROUPS.items():
        dbml.append('// ' + group)
        for name in names:
            t = TABLES[name]
            ddl, lines, checks = [], [], list(t['checks'])
            for c in t['columns'].values():
                opts = []
                for flag, label in [('pk','pk'), ('unique','unique'), ('increment','increment')]:
                    if c[flag]:
                        opts.append(label)
                if not c['nullable']:
                    opts.append('not null')
                if c['default'] is not None:
                    opts.append('default: ' + c['default'])
                if c['check']:
                    opts.append('check: ' + c['check'])
                    checks.append((f"ck_{name}_{c['name']}", c['check'].strip('`')))
                cn = quote('SQL: ON UPDATE CURRENT_TIMESTAMP') if c['on_update'] else c['note']
                if cn:
                    opts.append('note: ' + cn)
                lines.append(f"  {c['name']} {c['type']}" + (' [' + ', '.join(opts) + ']' if opts else ''))
                entry = f"  `{c['name']}` {c['type'].upper()} " + ('NULL' if c['nullable'] else 'NOT NULL')
                if c['increment']:
                    entry += ' AUTO_INCREMENT'
                if c['default'] is not None:
                    entry += ' DEFAULT ' + c['default'].strip('`')
                elif c['nullable'] and c['type'] == 'timestamp':
                    entry += ' DEFAULT NULL'
                if c['on_update']:
                    entry += ' ON UPDATE CURRENT_TIMESTAMP'
                if c['pk']:
                    entry += ' PRIMARY KEY'
                if c['unique']:
                    entry += ' UNIQUE'
                ddl.append(entry)
            if t['indexes']:
                lines.append('  indexes {')
                for i in t['indexes']:
                    c = ', '.join(i['columns'])
                    dc = '(' + c + ')' if len(i['columns']) > 1 else c
                    opts = (['pk'] if i['pk'] else []) + (['unique'] if i['unique'] else [])
                    if i['name']:
                        opts.append('name: ' + quote(i['name']))
                    lines.append('    ' + dc + ' [' + ', '.join(opts) + ']')
                    prefix = 'PRIMARY KEY' if i['pk'] else ('UNIQUE KEY' if i['unique'] else 'KEY')
                    nk = (' `' + i['name'] + '`') if i['name'] and not i['pk'] else ''
                    ddl.append('  ' + prefix + nk + ' (' + identifiers(i['columns']) + ')')
                lines.append('  }')
            if t['checks']:
                lines.append('  checks {')
                lines += [f'    `{expr}` [name: {quote(key)}]' for key, expr in t['checks']]
                lines.append('  }')
            for key, expr in checks:
                assert len(key) <= 64, key
                ddl.append(f'  CONSTRAINT `{key}` CHECK ({expr})')
            if t['note']:
                lines.append('  Note: ' + quote(t['note']))
            dbml.append(f'Table {name} {{\n' + '\n'.join(lines) + '\n}\n')
            sql.append(f'CREATE TABLE `{name}` (\n' + ',\n'.join(ddl) + '\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\n')
    def endpoint(table_name, columns):
        return table_name + '.' + (columns[0] if len(columns) == 1 else '(' + ', '.join(columns) + ')')
    for r in REFS:
        t = TABLES[r['child']]
        unique_keys = [{c['name']} for c in t['columns'].values() if c['pk'] or c['unique']]
        unique_keys += [set(i['columns']) for i in t['indexes'] if i['pk'] or i['unique']]
        left, right = endpoint(r['child'], r['columns']), endpoint(r['parent'], r['targets'])
        nullable = any(t['columns'][c]['nullable'] for c in r['columns'])
        if set(r['columns']) in unique_keys:
            relation = right + (' ?- ' if nullable else ' - ') + left
        else:
            relation = left + (' >? ' if nullable else ' > ') + right
        dbml.append(f"Ref {r['name']}: {relation} [delete: restrict, update: restrict]")
        sql.append(f"ALTER TABLE `{r['child']}` ADD CONSTRAINT `{r['name']}` FOREIGN KEY (" + identifiers(r['columns']) + f") REFERENCES `{r['parent']}` (" + identifiers(r['targets']) + ');')
    grouped = list(dbml)
    for name, (color, names) in GROUPS.items():
        grouped.append('\nTableGroup ' + name + ' [color: ' + color + '] {\n  ' + '\n  '.join(names) + '\n}')
    dbml.append('\n// Optional groups: bookmooch.grouped.dbml (requires TableGroup support).')
    (ROOT / 'schema.sql').write_text('\n'.join(sql) + '\n', encoding='utf-8')
    (ROOT / 'bookmooch.dbml').write_text('\n'.join(dbml) + '\n', encoding='utf-8')
    (ROOT / 'bookmooch.grouped.dbml').write_text('\n'.join(grouped) + '\n', encoding='utf-8')
    count = sum(len(t['columns']) for t in TABLES.values())
    constraint_count = sum(len(t['checks']) + sum(bool(c['check']) for c in t['columns'].values()) for t in TABLES.values())
    print(f'{len(TABLES)} tables, {count} columns, {len(REFS)} foreign keys, {constraint_count} CHECK constraints.')
