spring.application.name=comicworm
server.port=${SERVER_PORT:8080}
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.sql.init.mode=never

# JWT Configuration
# Secret Key t?i thi?u 256-bit (32 ký t? / bytes) ?? ??m b?o an toàn cho HMAC-SHA256
app.jwt.secretkey=

# Th?i gian h?t h?n c?a Access Token (ví d?: 15 phút = 15 * 60 * 1000 = 900000 ms)
app.jwt.expire.access.token=

# Th?i gian h?t h?n c?a Refresh Token (ví d?: 7 ngày = 7 * 24 * 60 * 60 * 1000 = 604800000 ms)
app.jwt.expire.refresh.token=

app.base.url=http://localhost:8080

# C?u hình Spring Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
# M?t kh?u ?ng d?ng (App Password t?o trong tài kho?n Google, không dùng m?t kh?u th??ng)
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true